languageCode: "ko-kr"
baseUrl: ""
title: "Antonio Min"
theme: "anubis"
paginate: 10
googleAnalytics: "UA-114342284-1"
enableRobotsTXT: true

menu:
  main:
  - identifier: About
    name: About
    title: About
    url: /about/
    weight: 0
  - identifier: Posts
    name: Posts
    title: Posts
    url: /posts/
    weight: 0

params:
  author: "Antonio Min"
  email: gvvvv1123@gmail.com # used for microformats
  description: ""
  dateFormat: "2006-01-02"
  customCSS:
    - css/override.css
  customJS:
    - js/load.js
  paginationSinglePost: true
  style: dark-without-switcher
  readMore: false # show read more button
  readNextPosts: 5  # show 5 related posts, 0 by default
  disableSummary: false
  copyCodeButton: true # true by default
  rssAsSocialIcon: true
  social:
  - id: github
    name: antoniomin
  - id: linkedin
    name: 병윤-민-a83b2b61

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown